trigger:
- master
- rel/*

pr:
- master
- rel/*

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool

- script: nbgv cloud
  displayName: Set Version

- task: UseDotNet@2
    displayName: 'Use .NET Core sdk 5.0'
    inputs:
      packageType: sdk
      version: 5.0.100

- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: build
    projects: src/*.sln
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack Behaviors
  inputs:
    command: pack
    packagesToPack: src/**/Microsoft.Xaml.Behaviors.csproj
    arguments: '--configuration $(buildConfiguration)'

- task: VSTest@2
  displayName: Run Tests
  inputs:
    testAssemblyVer2: |
     Test\**\$(BuildConfiguration)\*test*.dll
     !**\obj\**
    configuration: $(buildConfiguration)

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactType: container
    artifactName: artifacts